---
# The file contains the options for the release package
# Make sure to check the documentation at https://goreleaser.com
version: 2

before:
  hooks:
    - go mod tidy
builds:
  - id: sdafs
    main: ./cmd/sdafs
    goos:
      - linux
      - darwin
    ignore:
      - goarch: 386
      - goarch: arm
    ldflags:
      - -s -w -X main.Version={{ .Tag }}
  - id: csi-driver
    main: ./cmd/csi-driver
    goos:
      - linux
    ignore:
      - goarch: 386
      - goarch: arm
    ldflags:
      - -s -w -X main.Version={{ .Tag }}
archives:
  - id: sdafs
    ids:
      - sdafs
    name_template: >-
      sdafs_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip

  - id: csi-driver
    ids:
      - csi-driver
    name_template: >-
      csi-driver_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
        - zip
