---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-attacher-sdafs-sa
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-sdafs-cr
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "update", "patch", "create"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "patch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments", "volumeattachments/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "update", "patch", "create"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-attacher-role-binding
subjects:
  - kind: ServiceAccount
    name: csi-attacher-sdafs-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: csi-attacher-sdafs-cr
  apiGroup: rbac.authorization.k8s.io

---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-attacher-sdafs
  namespace: kube-system
  annotations:
    checkov.io/skip1: CKV_K8S_9=No good probes available
    checkov.io/skip2: CKV_K8S_8=No good probes available
    checkov.io/skip3: CKV_K8S_38=Is this probe broken?
    checkov.io/skip4: CKV_K8S_43=Prefer non-digests here
spec:
  selector:
    matchLabels:
      app: csi-sdafs
      role: systemservices
  template:
    metadata:
      labels:
        app: csi-sdafs
        role: systemservices
    spec:
      serviceAccount: csi-attacher-sdafs-sa
      automountServiceAccountToken: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 65534
        runAsGroup: 65535
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: "Exists"
      containers:
        - name: csi-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.9.0
          args:
            - "--v=4"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
            - "--http-endpoint=:4002"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/csi.sda.nbis.se/csi.sock
          imagePullPolicy: Always
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/csi.sda.nbis.se
          resources:
            requests:
              # Seems to use roughly 10 Mbyte in test environment
              memory: "128Mi"
              cpu: "0.01"
            limits:
              cpu: "0.1"
              memory: "1Gi"
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.3.0
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=4"
            - "--leader-election"
            - "--http-endpoint=:4001"
            - "--controller-publish-readonly=true"
            - "--node-deployment=true"
          env:
            - name: ADDRESS
              value: /var/lib/kubelet/plugins/csi.sda.nbis.se/csi.sock
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          imagePullPolicy: Always
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/csi.sda.nbis.se
          resources:
            requests:
              # Seems to use roughly 10 Mbyte in test environment
              memory: "128Mi"
              cpu: "0.01"
            limits:
              cpu: "0.1"
              memory: "1Gi"
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.sda.nbis.se
            type: DirectoryOrCreate
